name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ vars.DOCKER_HUB_USERNAME }}
        password: ${{ vars.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Build and Tag the Docker image
      run: |
        # Build the image and tag it with the commit SHA
        docker build -t ${{ vars.DOCKER_HUB_USERNAME }}/8-puzzle-cs:${{ github.sha }} .
        # Tag the image as 'latest'
        docker tag ${{ vars.DOCKER_HUB_USERNAME }}/8-puzzle-cs:${{ github.sha }} ${{ vars.DOCKER_HUB_USERNAME }}/8-puzzle-cs:latest

    - name: Push the Docker image
      run: |
        # Push both tags to Docker Hub
        docker push ${{ vars.DOCKER_HUB_USERNAME }}/8-puzzle-cs:${{ github.sha }}
        docker push ${{ vars.DOCKER_HUB_USERNAME }}/8-puzzle-cs:latest
